# Pandas

Difference between:
* df["c"] - Series 
* df[["c"]] - DataFrame


- & - result is when both conditions are true
- | - result is when either one is true.


Create a dataframe: 
csv_text = """
    column, column
    data, data
    data, data
"""

- df.columns - to check the column names
- df.dtypes
- df.info()
- df.shape
- df.describe

- df.loc[] - label-based
- df.iloc[] - position-based, index-based
- df.reset_index(drop=True) - resets the index back to it's old state

- df.value_counts()
- df.column.value_counts(normalize = True) - gives the percentage instead of counts.
- df.mean()

- df.sort_values()

- df.head()
- df.tail()

- df.to_numeric(df.column, errors = "coerce") - convert into numeric, errors = "coerce" turns different datatype into NaN
- pd.to_datetime(df.column, errors = "coerce") - converts into datetime

- df.isna() - takes into consideration the 0 or null values
- df.dt.year or df.dt.month or df.dt.day or df.dt.hour

- df.groupby()[].transform()

In [5]:
import pandas as pd
import io

csv_text = """
city,region,pop
Cebu,Visayas,964000
Davao,Mindanao,1777000
Iloilo,Visayas,457000
Baguio,Luzon,366000
Tacloban,Visayas,251000
"""

df = pd.read_csv(io.StringIO(csv_text))
print(df.head())
print(df.shape)

       city    region      pop
0      Cebu   Visayas   964000
1     Davao  Mindanao  1777000
2    Iloilo   Visayas   457000
3    Baguio     Luzon   366000
4  Tacloban   Visayas   251000
(5, 3)

In [7]:
import pandas as pd
import io

csv_text = """city,region,pop
Cebu,Visayas,964000
Davao,Mindanao,1777000
Iloilo,Visayas,457000
Baguio,Luzon,366000
Tacloban,Visayas,251000"""
df = pd.read_csv(io.StringIO(csv_text))
print(df)
print(df.columns.tolist())
print(df.dtypes)
print(df.shape)
print(df.describe().round())

       city    region      pop
0      Cebu   Visayas   964000
1     Davao  Mindanao  1777000
2    Iloilo   Visayas   457000
3    Baguio     Luzon   366000
4  Tacloban   Visayas   251000
['city', 'region', 'pop']
city      object
region    object
pop        int64
dtype: object
(5, 3)
             pop
count        5.0
mean    763000.0
std     628885.0
min     251000.0
25%     366000.0
50%     457000.0
75%     964000.0
max    1777000.0

In [ ]:
# print(df["pop"])
#print(df[["city", "pop"]])
#print(df.loc[0:2])
#print(df.iloc[0:2])

# print(df.loc[0:"region"])
#print(df.iloc[0:1])

# print(df.loc[0:2, ["city", "pop"]])
#print(df.iloc[0:2, [0,2]])

    city      pop
0   Cebu   964000
1  Davao  1777000

In [51]:
small = df[df["pop"] < 500000]
print(small.index.tolist())
print(small)
print(small.iloc[0]["city"])

try:
    small.loc[0]
except KeyError as e:
    print("KeyError:", e)

small = small.reset_index(drop=True)
print(small)

[2, 3, 4]
       city   region     pop
2    Iloilo  Visayas  457000
3    Baguio    Luzon  366000
4  Tacloban  Visayas  251000
Iloilo
KeyError: 0
       city   region     pop
0    Iloilo  Visayas  457000
1    Baguio    Luzon  366000
2  Tacloban  Visayas  251000

In [56]:
#print(df.loc[0])
#print(df.iloc[-1])

# print(df.loc[df["city"] == "Cebu"])

print(df["pop"])

0     964000
1    1777000
2     457000
3     366000
4     251000
Name: pop, dtype: int64

In [58]:
#print(df["pop"] > 1000000)
print(df[df["pop"] > 1000000])

    city    region      pop
1  Davao  Mindanao  1777000

In [67]:
big = df["pop"] > 500_000
vis = df["region"] == "Visayas"

print(df)
# print(df[big & vis])
# print(df[big | vis])

       city    region      pop
0      Cebu   Visayas   964000
1     Davao  Mindanao  1777000
2    Iloilo   Visayas   457000
3    Baguio     Luzon   366000
4  Tacloban   Visayas   251000

In [77]:
import pandas as pd

t = pd.DataFrame({"g": ["x", "x", "y", "y"],
                  "a": [1, 2, 3, 4]})

sub = t[t.g == "x"]
sub["a"] = 99
t.loc[t.g == "x", "a"] = 77
print("t:", t.a.tolist())
# print("sub:", sub.a.tolist())
# print("t  :", t.a.tolist())

t: [77, 77, 3, 4]

C:\Users\ASUS VivoBook\AppData\Local\Temp\ipykernel_22004\717638044.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  sub["a"] = 99

In [78]:
print(df["pop"].value_counts())

pop
964000     1
1777000    1
457000     1
366000     1
251000     1
Name: count, dtype: int64

In [79]:
print(df["pop"].mean())

763000.0

In [84]:
vis = df[df["region"] == "Visayas"]
print(vis)
print(vis["pop"].mean())

print(vis.sort_values("pop"))

       city   region     pop
0      Cebu  Visayas  964000
2    Iloilo  Visayas  457000
4  Tacloban  Visayas  251000
557333.3333333334
       city   region     pop
4  Tacloban  Visayas  251000
2    Iloilo  Visayas  457000
0      Cebu  Visayas  964000

In [87]:
import io, requests

url  = "https://portal.latarak.com/api/flood/export.csv"
resp = requests.get(url, timeout=60)
df   = pd.read_csv(io.StringIO(resp.text))

df.shape
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 34079 entries, 0 to 34078
Data columns (total 15 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   contract_id      34079 non-null  object
 1   description      34079 non-null  object
 2   category         34079 non-null  object
 3   status           34079 non-null  object
 4   budget           34079 non-null  float64
 5   amount_paid      34079 non-null  int64
 6   progress         34079 non-null  float64
 7   contractor       33203 non-null  object
 8   start_date       33106 non-null  object
 9   completion_date  27665 non-null  object
 10  year             34079 non-null  int64
 11  region           34079 non-null  object
 12  province         34079 non-null  object
 13  latitude         30884 non-null  float64
 14  longitude        30884 non-null  float64
dtypes: float64(4), int64(2), object(9)
memory usage: 3.9+ MB

In [105]:
df = pd.read_csv(io.StringIO(resp.text))
df["budget"] = pd.to_numeric(df.budget, errors = "coerce")
df["start_date"] = pd.to_datetime(df.start_date, errors = "coerce")

df.budget.isna().sum(), df.start_date.isna().sum

(np.int64(0),
 <bound method Series.sum of 0        False
 1        False
 2        False
 3        False
 4        False
          ...
 34074    False
 34075    False
 34076    False
 34077     True
 34078     True
 Name: start_date, Length: 34079, dtype: bool>)

In [97]:
import pandas as pd

s = pd.Series(['apple', '1.5', '42', 'N/A', '-3'])
numeric_s = pd.to_numeric(s, errors = "coerce")

# Using errors='coerce' turns 'apple' and 'N/A' into NaN
numeric_s = pd.to_numeric(s, errors='coerce')

print(numeric_s)

0     NaN
1     1.5
2    42.0
3     NaN
4    -3.0
dtype: float64

In [110]:
df.start_date.min(), df.start_date.max()

(Timestamp('2015-05-17 00:00:00'), Timestamp('2025-09-23 00:00:00'))

In [ ]:
df.start_date.dt.month.value_counts().sort_index()

start_date
1.0     1054
2.0     9416
3.0     7122
4.0     3972
5.0     2419
6.0     2401
7.0     2255
8.0      865
9.0      847
10.0     736
11.0     978
12.0    1041
Name: count, dtype: int64

In [120]:
df.status.value_counts()

status
Completed          27534
On-Going            5442
For Procurement      876
Terminated           131
Not Yet Started       96
Name: count, dtype: int64

In [123]:
df.nlargest(3, "budget")[["budget", "region"]]

             budget          region
18777  1.447500e+09  Central Office
33185  1.096255e+09  Central Office
28049  1.042783e+09  Central Office

In [124]:
df.nsmallest(3, "budget")

,contract_id,description,category,status,budget,amount_paid,progress,contractor,start_date,completion_date,year,region,province,latitude,longitude
123,18O00020,ORGANIZATIONAL OUTCOME 2 - PROTECT LIVES AND P...,Flood Control and Drainage,Terminated,0.0,0,0.0,STA. CLARA INTERNATIONAL CORPORATION (3872) / ...,2019-01-20,2020-09-11,2018,National Capital Region,National Capital Region,14.594312,120.966629
199,20OB0408,IMPROVEMENT OF MARIKINA RIVER FROM TAÑONG J. D...,Flood Control and Drainage,Terminated,0.0,0,0.0,ALPHA & OMEGA GEN. CONTRACTOR & DEVELOPMENT CO...,2020-11-25,2021-08-09,2020,National Capital Region,Metro Manila 1st DEO,14.624297,121.092872
645,20OB0183,"RIVER IMPROVEMENT ALONG MARIKINA RIVER, BRGY. ...",Flood Control and Drainage,Terminated,0.0,0,0.0,ALPHA & OMEGA GEN. CONTRACTOR & DEVELOPMENT CO...,2020-12-29,2021-08-09,2020,National Capital Region,Metro Manila 1st DEO,14.625350,121.090272

In [131]:
df[(df.region == "Region III") &
(df.budget > 1e8) & 
(df.status == "Completed")
][["region", "budget", "status"]]

           region        budget     status
87     Region III  2.701947e+08  Completed
504    Region III  1.447500e+08  Completed
699    Region III  1.003600e+08  Completed
1236   Region III  1.484986e+08  Completed
2698   Region III  1.447500e+08  Completed
...           ...           ...        ...
32766  Region III  1.515049e+08  Completed
33078  Region III  1.930000e+08  Completed
33372  Region III  2.171235e+08  Completed
33568  Region III  1.398074e+08  Completed
33672  Region III  1.447443e+08  Completed

[69 rows x 3 columns]

In [133]:
df.query("region == 'Region III' "
"and budget > 1e8"
"and status == 'Completed' "
)[["region", "budget", "status"]]

           region        budget     status
87     Region III  2.701947e+08  Completed
504    Region III  1.447500e+08  Completed
699    Region III  1.003600e+08  Completed
1236   Region III  1.484986e+08  Completed
2698   Region III  1.447500e+08  Completed
...           ...           ...        ...
32766  Region III  1.515049e+08  Completed
33078  Region III  1.930000e+08  Completed
33372  Region III  2.171235e+08  Completed
33568  Region III  1.398074e+08  Completed
33672  Region III  1.447443e+08  Completed

[69 rows x 3 columns]

In [137]:
df.region.describe()
df.describe()
df.describe(include="all")

,contract_id,description,category,status,budget,amount_paid,progress,contractor,start_date,completion_date,year,region,province,latitude,longitude
count,34079,34079,34079,34079,3.407900e+04,34079.0,34079.000000,33203,33106,27665,34079.000000,34079,34079,30884.000000,30884.000000
unique,34079,33325,17,5,NaN,NaN,NaN,4841,NaN,3385,NaN,18,216,NaN,NaN
top,22F00136,"MFO2-FLOOD MANAGEMENT SERVICES, CONSTRUCTION/M...",Flood Control and Drainage,Completed,NaN,NaN,NaN,ST. TIMOTHY CONSTRUCTION CORPORATION ([REVOKED...,NaN,2023-12-15,NaN,Region III,Bulacan 1st DEO,NaN,NaN
freq,1,26,33866,27534,NaN,NaN,NaN,345,NaN,72,NaN,5412,1293,NaN,NaN
mean,NaN,NaN,NaN,NaN,4.695234e+07,0.0,92.228051,NaN,2021-05-23 23:06:42.996435712,NaN,2021.124387,NaN,NaN,13.280522,122.195871
min,NaN,NaN,NaN,NaN,0.000000e+00,0.0,0.000000,NaN,2015-05-17 00:00:00,NaN,2016.000000,NaN,NaN,5.008394,117.061736
25%,NaN,NaN,NaN,NaN,1.464941e+07,0.0,100.000000,NaN,2019-05-31 00:00:00,NaN,2019.000000,NaN,NaN,10.897421,120.897795
50%,NaN,NaN,NaN,NaN,3.767623e+07,0.0,100.000000,NaN,2022-02-08 00:00:00,NaN,2022.000000,NaN,NaN,14.379413,121.235045
75%,NaN,NaN,NaN,NaN,6.754927e+07,0.0,100.000000,NaN,2023-12-21 00:00:00,NaN,2024.000000,NaN,NaN,15.151233,123.659587
max,NaN,NaN,NaN,NaN,1.447500e+09,0.0,100.000000,NaN,2025-09-23 00:00:00,NaN,2026.000000,NaN,NaN,20.791360,126.570333
std,NaN,NaN,NaN,NaN,4.859432e+07,0.0,23.487105,NaN,NaN,NaN,2.767364,NaN,NaN,3.123614,1.753098

In [141]:
df["contractor"].isna()

0        False
1        False
2        False
3        False
4        False
         ...
34074    False
34075    False
34076    False
34077     True
34078     True
Name: contractor, Length: 34079, dtype: bool

In [142]:
df[df["contractor"].isna()]

,contract_id,description,category,status,budget,amount_paid,progress,contractor,start_date,completion_date,year,region,province,latitude,longitude
27206,24AI0199,REPAIR/REHABILITATION OF BANK PROTECTION AT BR...,Flood Control and Drainage,For Procurement,0.0,0,0.0,NaN,NaT,NaN,2024,Region I,Pangasinan 3rd DEO,NaN,NaN
27216,25IE0055,"CONSTRUCTION OF TIDE PROTECTION EMBANKMENT, BR...",Flood Control and Drainage,For Procurement,0.0,0,0.0,NaN,NaT,NaN,2025,Region VIII,Leyte 3rd DEO,NaN,NaN
27219,24F00310,REHABILITATION/RECONSTRUCTION OF FLOOD CONTROL...,Flood Control and Drainage,For Procurement,0.0,0,0.0,NaN,NaT,NaN,2024,Region V,Region V,NaN,NaN
27224,25KL0098,CONSTRUCTION OF FLOOD CONTROL STRUCTURE (UPSTR...,Flood Control and Drainage,For Procurement,0.0,0,0.0,NaN,NaT,NaN,2025,Region X,Misamis Oriental 2nd DEO,NaN,NaN
27232,24I00330,REPAIR/REHABILITATION OF PUNOD RIVER 2 REVETME...,Flood Control and Drainage,For Procurement,0.0,0,0.0,NaN,NaT,NaN,2024,Region VIII,Region VIII,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34040,24PL0126,ORGANIZATIONAL OUTCOME 2: PROTECT LIVES AND PR...,Flood Control and Drainage,For Procurement,0.0,0,0.0,NaN,NaT,NaN,2024,Cordillera Administrative Region,Lower Kalinga DEO,NaN,NaN
34044,25D00087,CONSTRUCTION OF FLOOD CONTROL STRUCTURE ALONG ...,Flood Control and Drainage,For Procurement,0.0,0,0.0,NaN,NaT,NaN,2025,Region IV-A,Region IV-A,NaN,NaN
34070,24C00668,CONVERGENCE AND SPECIAL SUPPORT PROGRAM-SUSTAI...,Flood Control and Drainage,For Procurement,0.0,0,0.0,NaN,NaT,NaN,2024,Region III,Region III,NaN,NaN
34077,24AB0129,CONSTRUCTION/UPGRADING/REHABILITATION OF DRAIN...,Flood Control and Drainage,For Procurement,0.0,0,0.0,NaN,NaT,NaN,2024,Region I,Ilocos Norte 2nd DEO,NaN,NaN
34078,24AF0213,REHABILITATION OF DAMAGED SHORE PROTECTION WOR...,Flood Control and Drainage,For Procurement,0.0,0,0.0,NaN,NaT,NaN,2024,Region I,La Union 2nd DEO,NaN,NaN

In [158]:
df.contractor.fillna("Not yet awarded").value_counts()

df.contractor.isna().value_counts()

contractor
False    33203
True       876
Name: count, dtype: int64

In [144]:
df[df["contractor"].isna()]

,contract_id,description,category,status,budget,amount_paid,progress,contractor,start_date,completion_date,year,region,province,latitude,longitude
27206,24AI0199,REPAIR/REHABILITATION OF BANK PROTECTION AT BR...,Flood Control and Drainage,For Procurement,0.0,0,0.0,NaN,NaT,NaN,2024,Region I,Pangasinan 3rd DEO,NaN,NaN
27216,25IE0055,"CONSTRUCTION OF TIDE PROTECTION EMBANKMENT, BR...",Flood Control and Drainage,For Procurement,0.0,0,0.0,NaN,NaT,NaN,2025,Region VIII,Leyte 3rd DEO,NaN,NaN
27219,24F00310,REHABILITATION/RECONSTRUCTION OF FLOOD CONTROL...,Flood Control and Drainage,For Procurement,0.0,0,0.0,NaN,NaT,NaN,2024,Region V,Region V,NaN,NaN
27224,25KL0098,CONSTRUCTION OF FLOOD CONTROL STRUCTURE (UPSTR...,Flood Control and Drainage,For Procurement,0.0,0,0.0,NaN,NaT,NaN,2025,Region X,Misamis Oriental 2nd DEO,NaN,NaN
27232,24I00330,REPAIR/REHABILITATION OF PUNOD RIVER 2 REVETME...,Flood Control and Drainage,For Procurement,0.0,0,0.0,NaN,NaT,NaN,2024,Region VIII,Region VIII,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34040,24PL0126,ORGANIZATIONAL OUTCOME 2: PROTECT LIVES AND PR...,Flood Control and Drainage,For Procurement,0.0,0,0.0,NaN,NaT,NaN,2024,Cordillera Administrative Region,Lower Kalinga DEO,NaN,NaN
34044,25D00087,CONSTRUCTION OF FLOOD CONTROL STRUCTURE ALONG ...,Flood Control and Drainage,For Procurement,0.0,0,0.0,NaN,NaT,NaN,2025,Region IV-A,Region IV-A,NaN,NaN
34070,24C00668,CONVERGENCE AND SPECIAL SUPPORT PROGRAM-SUSTAI...,Flood Control and Drainage,For Procurement,0.0,0,0.0,NaN,NaT,NaN,2024,Region III,Region III,NaN,NaN
34077,24AB0129,CONSTRUCTION/UPGRADING/REHABILITATION OF DRAIN...,Flood Control and Drainage,For Procurement,0.0,0,0.0,NaN,NaT,NaN,2024,Region I,Ilocos Norte 2nd DEO,NaN,NaN
34078,24AF0213,REHABILITATION OF DAMAGED SHORE PROTECTION WOR...,Flood Control and Drainage,For Procurement,0.0,0,0.0,NaN,NaT,NaN,2024,Region I,La Union 2nd DEO,NaN,NaN

In [151]:
df.budget.fillna(df.budget.median())

0        2.798396e+08
1        1.881518e+07
2        9.075766e+07
3        7.233500e+07
4        2.350286e+07
             ...
34074    1.838542e+07
34075    1.465086e+07
34076    1.960000e+07
34077    0.000000e+00
34078    0.000000e+00
Name: budget, Length: 34079, dtype: float64

In [162]:
df.region.value_counts().sort_index()

region
Central Office                       180
Cordillera Administrative Region    1247
National Capital Region             3925
Negros Island Region                 944
Region I                            3502
Region II                           1620
Region III                          5412
Region IV-A                         3452
Region IV-B                         1467
Region IX                            774
Region V                            2814
Region VI                           1088
Region VII                          1558
Region VIII                         1935
Region X                            1157
Region XI                           1329
Region XII                           813
Region XIII                          862
Name: count, dtype: int64

In [163]:
df.budget.fillna(
    df.groupby("region").budget.transform("median"))

0        2.798396e+08
1        1.881518e+07
2        9.075766e+07
3        7.233500e+07
4        2.350286e+07
             ...
34074    1.838542e+07
34075    1.465086e+07
34076    1.960000e+07
34077    0.000000e+00
34078    0.000000e+00
Name: budget, Length: 34079, dtype: float64

In [165]:

before = df.budget.isna().sum()
print(before)

0

In [172]:
import pandas as pd
import numpy as np

# Sample data
sample = pd.DataFrame({
    'Department': ['Sales', 'Sales', 'IT', 'IT', 'HR'],
    'Employee': ['Alice', 'Bob', 'Charlie', 'David', 'Eva'],
    'Salary': [50000, 60000, 70000, 80000, 55000]
})

# # Calculate the average salary of each department and match it to each employee
sample['Dept_Avg_Salary'] = sample.groupby('Department').Salary.transform('mean')

print(sample)

  Department Employee  Salary  Dept_Avg_Salary
0      Sales    Alice   50000          55000.0
1      Sales      Bob   60000          55000.0
2         IT  Charlie   70000          75000.0
3         IT    David   80000          75000.0
4         HR      Eva   55000          55000.0

# EXERCISE:

In [173]:
import pandas as pd
import io

csv_text = """
employee_id,name,department,salary,start_date,budget,status
101,Ana,IT,50000,2023-01-15,100000,Active
102,Ben,HR,45000,2023-03-20,85000,Active
103,Cara,IT,invalid,2023-01-22,120000,Inactive
104,Dan,Finance,70000,bad_date,95000,Active
105,Ella,IT,65000,2023-05-18,not_available,Inactive
106,Frank,HR,55000,2023-03-11,85000,Active
107,Gina,Finance,72000,2023-07-01,110000,Active
108,Hank,IT,48000,,100000,Inactive
"""

df = pd.read_csv(io.StringIO(csv_text))

In [174]:
print(df)

   employee_id   name department   salary  start_date         budget    status
0          101    Ana         IT    50000  2023-01-15         100000    Active
1          102    Ben         HR    45000  2023-03-20          85000    Active
2          103   Cara         IT  invalid  2023-01-22         120000  Inactive
3          104    Dan    Finance    70000    bad_date          95000    Active
4          105   Ella         IT    65000  2023-05-18  not_available  Inactive
5          106  Frank         HR    55000  2023-03-11          85000    Active
6          107   Gina    Finance    72000  2023-07-01         110000    Active
7          108   Hank         IT    48000         NaN         100000  Inactive

In [177]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   employee_id  8 non-null      int64
 1   name         8 non-null      object
 2   department   8 non-null      object
 3   salary       8 non-null      object
 4   start_date   7 non-null      object
 5   budget       8 non-null      object
 6   status       8 non-null      object
dtypes: int64(1), object(6)
memory usage: 580.0+ bytes

In [179]:
df.describe()

       employee_id
count      8.00000
mean     104.50000
std        2.44949
min      101.00000
25%      102.75000
50%      104.50000
75%      106.25000
max      108.00000

In [188]:
df["salary"] = pd.to_numeric(df["salary"], errors = "coerce")

print(df)

   employee_id   name department   salary  start_date         budget    status
0          101    Ana         IT  50000.0  2023-01-15         100000    Active
1          102    Ben         HR  45000.0  2023-03-20          85000    Active
2          103   Cara         IT      NaN  2023-01-22         120000  Inactive
3          104    Dan    Finance  70000.0    bad_date          95000    Active
4          105   Ella         IT  65000.0  2023-05-18  not_available  Inactive
5          106  Frank         HR  55000.0  2023-03-11          85000    Active
6          107   Gina    Finance  72000.0  2023-07-01         110000    Active
7          108   Hank         IT  48000.0         NaN         100000  Inactive

In [189]:
df["budget"] = pd.to_numeric(df["budget"], errors = "coerce")
print(df)

   employee_id   name department   salary  start_date    budget    status
0          101    Ana         IT  50000.0  2023-01-15  100000.0    Active
1          102    Ben         HR  45000.0  2023-03-20   85000.0    Active
2          103   Cara         IT      NaN  2023-01-22  120000.0  Inactive
3          104    Dan    Finance  70000.0    bad_date   95000.0    Active
4          105   Ella         IT  65000.0  2023-05-18       NaN  Inactive
5          106  Frank         HR  55000.0  2023-03-11   85000.0    Active
6          107   Gina    Finance  72000.0  2023-07-01  110000.0    Active
7          108   Hank         IT  48000.0         NaN  100000.0  Inactive

In [190]:
df["start_date"] = pd.to_datetime(df["start_date"], errors = "coerce")
print(df)

   employee_id   name department   salary start_date    budget    status
0          101    Ana         IT  50000.0 2023-01-15  100000.0    Active
1          102    Ben         HR  45000.0 2023-03-20   85000.0    Active
2          103   Cara         IT      NaN 2023-01-22  120000.0  Inactive
3          104    Dan    Finance  70000.0        NaT   95000.0    Active
4          105   Ella         IT  65000.0 2023-05-18       NaN  Inactive
5          106  Frank         HR  55000.0 2023-03-11   85000.0    Active
6          107   Gina    Finance  72000.0 2023-07-01  110000.0    Active
7          108   Hank         IT  48000.0        NaT  100000.0  Inactive

In [196]:
print(df)

   employee_id   name department   salary start_date    budget    status
0          101    Ana         IT  50000.0 2023-01-15  100000.0    Active
1          102    Ben         HR  45000.0 2023-03-20   85000.0    Active
2          103   Cara         IT      NaN 2023-01-22  120000.0  Inactive
3          104    Dan    Finance  70000.0        NaT   95000.0    Active
4          105   Ella         IT  65000.0 2023-05-18       NaN  Inactive
5          106  Frank         HR  55000.0 2023-03-11   85000.0    Active
6          107   Gina    Finance  72000.0 2023-07-01  110000.0    Active
7          108   Hank         IT  48000.0        NaT  100000.0  Inactive

In [201]:
df.loc[0:3, ["name", "salary"]]

   name   salary
0   Ana  50000.0
1   Ben  45000.0
2  Cara      NaN
3   Dan  70000.0

In [203]:
df.iloc[0:5, 0:3]

   employee_id  name department
0          101   Ana         IT
1          102   Ben         HR
2          103  Cara         IT
3          104   Dan    Finance
4          105  Ella         IT

In [209]:
a = df[df["department"] == "IT"]

b = a.reset_index(drop= True)
print(b)

   employee_id  name department   salary start_date    budget    status
0          101   Ana         IT  50000.0 2023-01-15  100000.0    Active
1          103  Cara         IT      NaN 2023-01-22  120000.0  Inactive
2          105  Ella         IT  65000.0 2023-05-18       NaN  Inactive
3          108  Hank         IT  48000.0        NaT  100000.0  Inactive

In [215]:
x = df["department"] == "IT"
y = df["status"] == "Active"
print(df[x & y])

   employee_id name department   salary start_date    budget  status
0          101  Ana         IT  50000.0 2023-01-15  100000.0  Active

In [217]:
q = df["department"] == "Finance"
w = df["department"] == "HR"

print(df[q | w])

   employee_id   name department   salary start_date    budget  status
1          102    Ben         HR  45000.0 2023-03-20   85000.0  Active
3          104    Dan    Finance  70000.0        NaT   95000.0  Active
5          106  Frank         HR  55000.0 2023-03-11   85000.0  Active
6          107   Gina    Finance  72000.0 2023-07-01  110000.0  Active

In [219]:
df.department.value_counts(normalize = True)

department
IT         0.50
HR         0.25
Finance    0.25
Name: proportion, dtype: float64